services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: cluster23
      POSTGRES_PASSWORD: cluster23
      POSTGRES_DB: quant-helper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

#  api:
#    build:
#      context: .
#      dockerfile: ./docker/api/Dockerfile
#    container_name: api
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quant-helper
#      SPRING_DATASOURCE_USERNAME: cluster23
#      SPRING_DATASOURCE_PASSWORD: cluster23
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    networks:
#      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: